### ISSUE TITLE
Migrate to Nextclade v3

### ISSUE THREAD

**Issue by joverlee521** [nextstrain/ncov#1157]
[Migration to Nextclade v3 guide](https://docs.nextstrain.org/projects/nextclade/en/stable/user/migration-v3.html) for reference.

## TODOs

- [x] remove `use_nextalign` config from build.yaml files (the use of the config was removed in https://github.com/nextstrain/ncov/pull/630)
- [x] ~update [mutation_summary.py](https://github.com/nextstrain/ncov/blob/7e594bc85ac82c4d499555f5288ffd6628dbd141/scripts/mutation_summary.py) to work with Nextclade v3 outputs~ Remove mutation_summary.py and related rules
- [x] update nextclade2/nextalign commands in workflow rules
- [x] remove references to "nextalign" in docs
- [x] update nextclade dependencies [workflow/envs/nextstrain.yaml](https://github.com/nextstrain/ncov/blob/7e594bc85ac82c4d499555f5288ffd6628dbd141/workflow/envs/nextstrain.yaml#L10-L11)
- [ ] major release of the workflow
